# This is a comment.
network:
   name: us-east1
   instance_ip_mode: internal
   instance_tag: aef-instance
   subnetwork_name: default
   session_affinity: true
   forwarded_ports:
    - 2222
    - HOST_PORT: 3024
    - 2222 / tcp
    - HOST_PORT:3024/udp